// Code generated by mockery v1.0.0
package mocks

import (
	context "context"

	common "github.com/uber/aresdb/broker/common"

	mock "github.com/stretchr/testify/mock"

	querycommon "github.com/uber/aresdb/query/common"
)

// BlockingPlanNode is an autogenerated mock type for the BlockingPlanNode type
type BlockingPlanNode struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *BlockingPlanNode) Add(_a0 ...common.BlockingPlanNode) { _ = "STUB: not implemented"; return }

// Children provides a mock function with given fields:
func (_m *BlockingPlanNode) Children() []common.BlockingPlanNode {
	_ = "STUB: not implemented"
	return nil
}

// Execute provides a mock function with given fields: ctx
func (_m *BlockingPlanNode) Execute(ctx context.Context) (querycommon.AQLQueryResult, error) {
	_ = "STUB: not implemented"
	return *new(querycommon.AQLQueryResult), nil
}
