// Code generated by mockery v1.0.0
package mocks

import (
	context "context"

	common "github.com/uber/aresdb/broker/common"

	mock "github.com/stretchr/testify/mock"

	querycommon "github.com/uber/aresdb/query/common"
)

// MergeNode is an autogenerated mock type for the MergeNode type
type MergeNode struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *MergeNode) Add(_a0 ...common.BlockingPlanNode) { _ = "STUB: not implemented"; return }

// AggType provides a mock function with given fields:
func (_m *MergeNode) AggType() common.AggType {
	_ = "STUB: not implemented"
	return *new(common.AggType)
}

// Children provides a mock function with given fields:
func (_m *MergeNode) Children() []common.BlockingPlanNode { _ = "STUB: not implemented"; return nil }

// Execute provides a mock function with given fields: ctx
func (_m *MergeNode) Execute(ctx context.Context) (querycommon.AQLQueryResult, error) {
	_ = "STUB: not implemented"
	return *new(querycommon.AQLQueryResult), nil
}
