// Code generated by mockery v1.0.0
package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// QueryExecutor is an autogenerated mock type for the QueryExecutor type
type QueryExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, namespace, sqlQuery, w
func (_m *QueryExecutor) Execute(ctx context.Context, namespace string, sqlQuery string, w http.ResponseWriter) error {
	_ = "STUB: not implemented"
	return nil
}
