// Code generated by mockery v1.0.0
package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StreamingPlanNode is an autogenerated mock type for the StreamingPlanNode type
type StreamingPlanNode struct {
	mock.Mock
}

// Execute provides a mock function with given fields: writer
func (_m *StreamingPlanNode) Execute(writer io.Writer) error { _ = "STUB: not implemented"; return nil }
