// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/metastore/common"

	models "github.com/uber/aresdb/controller/models"
)

// ControllerClient is an autogenerated mock type for the ControllerClient type
type ControllerClient struct {
	mock.Mock
}

// ExtendEnumCases provides a mock function with given fields: tableName, columnName, enumCases
func (_m *ControllerClient) ExtendEnumCases(tableName string, columnName string, enumCases []string) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FetchAllEnums provides a mock function with given fields: tableName, columnName
func (_m *ControllerClient) FetchAllEnums(tableName string, columnName string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FetchAllSchemas provides a mock function with given fields:
func (_m *ControllerClient) FetchAllSchemas() ([]*common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FetchSchema provides a mock function with given fields: table
func (_m *ControllerClient) FetchSchema(table string) (*common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAllSchema provides a mock function with given fields: namespace
func (_m *ControllerClient) GetAllSchema(namespace string) ([]common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAssignment provides a mock function with given fields: jobNamespace, instance
func (_m *ControllerClient) GetAssignment(jobNamespace string, instance string) (*models.IngestionAssignment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAssignmentHash provides a mock function with given fields: jobNamespace, instance
func (_m *ControllerClient) GetAssignmentHash(jobNamespace string, instance string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetNamespaces provides a mock function with given fields:
func (_m *ControllerClient) GetNamespaces() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSchemaHash provides a mock function with given fields: namespace
func (_m *ControllerClient) GetSchemaHash(namespace string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}
