//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package mocks is generated by mockery v1.0.0
package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FileInfo is an autogenerated mock type for the FileInfo type
type FileInfo struct {
	mock.Mock
}

// IsDir provides a mock function with given fields:
func (_m *FileInfo) IsDir() bool { _ = "STUB: not implemented"; return false }

// ModTime provides a mock function with given fields:
func (_m *FileInfo) ModTime() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Mode provides a mock function with given fields:
func (_m *FileInfo) Mode() os.FileMode { _ = "STUB: not implemented"; return *new(os.FileMode) }

// Name provides a mock function with given fields:
func (_m *FileInfo) Name() string { _ = "STUB: not implemented"; return "" }

// Size provides a mock function with given fields:
func (_m *FileInfo) Size() int64 { _ = "STUB: not implemented"; return 0 }

// Sys provides a mock function with given fields:
func (_m *FileInfo) Sys() interface{} { _ = "STUB: not implemented"; return nil }
