//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package mocks generated by mockery v1.0.0
package mocks

import (
	io "io"

	os "os"

	mock "github.com/stretchr/testify/mock"
)

// FileSystem is an autogenerated mock type for the FileSystem type
type FileSystem struct {
	mock.Mock
}

// Mkdir provides a mock function with given fields: name, perm
func (_m *FileSystem) Mkdir(name string, perm os.FileMode) error {
	_ = "STUB: not implemented"
	return nil
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *FileSystem) MkdirAll(path string, perm os.FileMode) error {
	_ = "STUB: not implemented"
	return nil
}

// OpenFileForWrite provides a mock function with given fields: name, flag, perm
func (_m *FileSystem) OpenFileForWrite(name string, flag int, perm os.FileMode) (io.WriteCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.WriteCloser), nil
}

// ReadDir provides a mock function with given fields: dirname
func (_m *FileSystem) ReadDir(dirname string) ([]os.FileInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadFile provides a mock function with given fields: filename
func (_m *FileSystem) ReadFile(filename string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Remove provides a mock function with given fields: path
func (_m *FileSystem) Remove(path string) error { _ = "STUB: not implemented"; return nil }

// RemoveAll provides a mock function with given fields: path
func (_m *FileSystem) RemoveAll(path string) error { _ = "STUB: not implemented"; return nil }

// Stat provides a mock function with given fields: path
func (_m *FileSystem) Stat(path string) (os.FileInfo, error) {
	_ = "STUB: not implemented"
	return *new(os.FileInfo), nil
}
