//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WriteSyncCloser is an autogenerated mock type for the WriteSyncCloser type
type WriteSyncCloser struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *WriteSyncCloser) Close() error { _ = "STUB: not implemented"; return nil }

// Sync provides a mock function with given fields:
func (_m *WriteSyncCloser) Sync() error { _ = "STUB: not implemented"; return nil }

// Write provides a mock function with given fields: p
func (_m *WriteSyncCloser) Write(p []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }
