// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// BootStrapToken is an autogenerated mock type for the BootStrapToken type
type BootStrapToken struct {
	mock.Mock
}

// AcquireToken provides a mock function with given fields: table, shard
func (_m *BootStrapToken) AcquireToken(table string, shard uint32) bool {
	_ = "STUB: not implemented"
	return false
}

// ReleaseToken provides a mock function with given fields: table, shard
func (_m *BootStrapToken) ReleaseToken(table string, shard uint32) {
	_ = "STUB: not implemented"
	return
}
