// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// EnumUpdater is an autogenerated mock type for the EnumUpdater type
type EnumUpdater struct {
	mock.Mock
}

// UpdateEnum provides a mock function with given fields: table, column, enumList
func (_m *EnumUpdater) UpdateEnum(table string, column string, enumList []string) error {
	_ = "STUB: not implemented"
	return nil
}
