// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/memstore/common"
)

// HostMemoryManager is an autogenerated mock type for the HostMemoryManager type
type HostMemoryManager struct {
	mock.Mock
}

// GetArchiveMemoryUsageByTableShard provides a mock function with given fields:
func (_m *HostMemoryManager) GetArchiveMemoryUsageByTableShard() (map[string]map[string]*common.ColumnMemoryUsage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReportManagedObject provides a mock function with given fields: table, shard, batchID, columnID, bytes
func (_m *HostMemoryManager) ReportManagedObject(table string, shard int, batchID int, columnID int, bytes int64) {
	_ = "STUB: not implemented"
	return
}

// ReportUnmanagedSpaceUsageChange provides a mock function with given fields: bytes
func (_m *HostMemoryManager) ReportUnmanagedSpaceUsageChange(bytes int64) {
	_ = "STUB: not implemented"

	// Start provides a mock function with given fields:
	return
}

func (_m *HostMemoryManager) Start() {
	_ = "STUB: not implemented"

	// Stop provides a mock function with given fields:
	return
}

func (_m *HostMemoryManager) Stop() {
	_ = "STUB: not implemented"

	// TriggerEviction provides a mock function with given fields:
	return
}

func (_m *HostMemoryManager) TriggerEviction() {
	_ = "STUB: not implemented"

	// TriggerPreload provides a mock function with given fields: tableName, columnID, oldPreloadingDays, newPreloadingDays
	return
}

func (_m *HostMemoryManager) TriggerPreload(tableName string, columnID int, oldPreloadingDays int, newPreloadingDays int) {
	_ = "STUB: not implemented"
	return
}
