// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// ListVectorParty is an autogenerated mock type for the ListVectorParty type
type ListVectorParty struct {
	mock.Mock
}

// GetListValue provides a mock function with given fields: row
func (_m *ListVectorParty) GetListValue(row int) (unsafe.Pointer, bool) {
	_ = "STUB: not implemented"
	return *new(unsafe.Pointer), false
}

// SetListValue provides a mock function with given fields: row, val, valid
func (_m *ListVectorParty) SetListValue(row int, val unsafe.Pointer, valid bool) {
	_ = "STUB: not implemented"
	return
}
