// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"io"
	"os"
	"unsafe"

	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/memstore/common"
)

// LiveVectorParty is an autogenerated mock type for the LiveVectorParty type
type LiveVectorParty struct {
	mock.Mock
}

// Allocate provides a mock function with given fields: hasCount
func (_m *LiveVectorParty) Allocate(hasCount bool) { _ = "STUB: not implemented"; return }

// AsList provides a mock function with given fields:
func (_m *LiveVectorParty) AsList() common.ListVectorParty {
	_ = "STUB: not implemented"
	return *new(common.ListVectorParty)
}

// Dump provides a mock function with given fields: file
func (_m *LiveVectorParty) Dump(file *os.File) {
	_ = "STUB: not implemented"

	// Equals provides a mock function with given fields: other
	return
}

func (_m *LiveVectorParty) Equals(other common.VectorParty) bool {
	_ = "STUB: not implemented"
	return false
}

// GetBytes provides a mock function with given fields:
func (_m *LiveVectorParty) GetBytes() int64 { _ = "STUB: not implemented"; return 0 }

// GetDataType provides a mock function with given fields:
func (_m *LiveVectorParty) GetDataType() common.DataType {
	_ = "STUB: not implemented"
	return *new(common.DataType)
}

// GetDataValue provides a mock function with given fields: offset
func (_m *LiveVectorParty) GetDataValue(offset int) common.DataValue {
	_ = "STUB: not implemented"
	return *new(common.DataValue)
}

// GetDataValueByRow provides a mock function with given fields: row
func (_m *LiveVectorParty) GetDataValueByRow(row int) common.DataValue {
	_ = "STUB: not implemented"
	return *new(common.DataValue)
}

// GetLength provides a mock function with given fields:
func (_m *LiveVectorParty) GetLength() int { _ = "STUB: not implemented"; return 0 }

// GetMinMaxValue provides a mock function with given fields:
func (_m *LiveVectorParty) GetMinMaxValue() (uint32, uint32) {
	_ = "STUB: not implemented"
	return 0, 0
}

// GetNonDefaultValueCount provides a mock function with given fields:
func (_m *LiveVectorParty) GetNonDefaultValueCount() int { _ = "STUB: not implemented"; return 0 }

// GetValidity provides a mock function with given fields: offset
func (_m *LiveVectorParty) GetValidity(offset int) bool { _ = "STUB: not implemented"; return false }

// GetValue provides a mock function with given fields: offset
func (_m *LiveVectorParty) GetValue(offset int) (unsafe.Pointer, bool) {
	_ = "STUB: not implemented"
	return *new(unsafe.Pointer), false
}

// IsList provides a mock function with given fields:
func (_m *LiveVectorParty) IsList() bool { _ = "STUB: not implemented"; return false }

// Read provides a mock function with given fields: reader, serializer
func (_m *LiveVectorParty) Read(reader io.Reader, serializer common.VectorPartySerializer) error {
	_ = "STUB: not implemented"
	return nil
}

// SafeDestruct provides a mock function with given fields:
func (_m *LiveVectorParty) SafeDestruct() {
	_ = "STUB: not implemented"

	// SetBool provides a mock function with given fields: offset, val, valid
	return
}

func (_m *LiveVectorParty) SetBool(offset int, val bool, valid bool) {
	_ = "STUB: not implemented"
	return
}

// SetDataValue provides a mock function with given fields: offset, value, countsUpdateMode, counts
func (_m *LiveVectorParty) SetDataValue(offset int, value common.DataValue, countsUpdateMode common.ValueCountsUpdateMode, counts ...uint32) {
	_ = "STUB: not implemented"
	return
}

// SetGoValue provides a mock function with given fields: offset, val, valid
func (_m *LiveVectorParty) SetGoValue(offset int, val common.GoDataValue, valid bool) {
	_ = "STUB: not implemented"
	return
}

// SetValue provides a mock function with given fields: offset, val, valid
func (_m *LiveVectorParty) SetValue(offset int, val unsafe.Pointer, valid bool) {
	_ = "STUB: not implemented"
	return
}

// Slice provides a mock function with given fields: startRow, numRows
func (_m *LiveVectorParty) Slice(startRow int, numRows int) common.SlicedVector {
	_ = "STUB: not implemented"
	return *new(common.SlicedVector)
}

// Write provides a mock function with given fields: writer
func (_m *LiveVectorParty) Write(writer io.Writer) error { _ = "STUB: not implemented"; return nil }
