// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/memstore/common"
)

// PrimaryKey is an autogenerated mock type for the PrimaryKey type
type PrimaryKey struct {
	mock.Mock
}

// AllocatedBytes provides a mock function with given fields:
func (_m *PrimaryKey) AllocatedBytes() uint { _ = "STUB: not implemented"; return 0 }

// Capacity provides a mock function with given fields:
func (_m *PrimaryKey) Capacity() uint { _ = "STUB: not implemented"; return 0 }

// Delete provides a mock function with given fields: key
func (_m *PrimaryKey) Delete(key common.Key) {
	_ = "STUB: not implemented"

	// Destruct provides a mock function with given fields:
	return
}

func (_m *PrimaryKey) Destruct() {
	_ = "STUB: not implemented"

	// Find provides a mock function with given fields: key
	return
}

func (_m *PrimaryKey) Find(key common.Key) (common.RecordID, bool) {
	_ = "STUB: not implemented"
	return *new(common.RecordID), false
}

// FindOrInsert provides a mock function with given fields: key, value, eventTime
func (_m *PrimaryKey) FindOrInsert(key common.Key, value common.RecordID, eventTime uint32) (bool, common.RecordID, error) {
	_ = "STUB: not implemented"
	return false, *new(common.RecordID), nil
}

// GetEventTimeCutoff provides a mock function with given fields:
func (_m *PrimaryKey) GetEventTimeCutoff() uint32 { _ = "STUB: not implemented"; return 0 }

// LockForTransfer provides a mock function with given fields:
func (_m *PrimaryKey) LockForTransfer() common.PrimaryKeyData {
	_ = "STUB: not implemented"
	return *new(common.PrimaryKeyData)
}

// Size provides a mock function with given fields:
func (_m *PrimaryKey) Size() uint { _ = "STUB: not implemented"; return 0 }

// UnlockAfterTransfer provides a mock function with given fields:
func (_m *PrimaryKey) UnlockAfterTransfer() {
	_ = "STUB: not implemented"

	// Update provides a mock function with given fields: key, value
	return
}

func (_m *PrimaryKey) Update(key common.Key, value common.RecordID) bool {
	_ = "STUB: not implemented"
	return false
}

// UpdateEventTimeCutoff provides a mock function with given fields: eventTimeCutoff
func (_m *PrimaryKey) UpdateEventTimeCutoff(eventTimeCutoff uint32) {
	_ = "STUB: not implemented"
	return
}
