// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/memstore/common"
)

// TableSchemaReader is an autogenerated mock type for the TableSchemaReader type
type TableSchemaReader struct {
	mock.Mock
}

// GetSchema provides a mock function with given fields: table
func (_m *TableSchemaReader) GetSchema(table string) (*common.TableSchema, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSchemas provides a mock function with given fields:
func (_m *TableSchemaReader) GetSchemas() map[string]*common.TableSchema {
	_ = "STUB: not implemented"
	return nil
}

// Lock provides a mock function with given fields:
func (_m *TableSchemaReader) Lock() {
	_ = "STUB: not implemented"

	// RLock provides a mock function with given fields:
	return
}

func (_m *TableSchemaReader) RLock() {
	_ = "STUB: not implemented"

	// RUnlock provides a mock function with given fields:
	return
}

func (_m *TableSchemaReader) RUnlock() {
	_ = "STUB: not implemented"

	// Unlock provides a mock function with given fields:
	return
}

func (_m *TableSchemaReader) Unlock() { _ = "STUB: not implemented"; return }
