// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"io"
	"os"

	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/memstore/common"
)

// VectorParty is an autogenerated mock type for the VectorParty type
type VectorParty struct {
	mock.Mock
}

// Allocate provides a mock function with given fields: hasCount
func (_m *VectorParty) Allocate(hasCount bool) { _ = "STUB: not implemented"; return }

// AsList provides a mock function with given fields:
func (_m *VectorParty) AsList() common.ListVectorParty {
	_ = "STUB: not implemented"
	return *new(common.ListVectorParty)
}

// Dump provides a mock function with given fields: file
func (_m *VectorParty) Dump(file *os.File) {
	_ = "STUB: not implemented"

	// Equals provides a mock function with given fields: other
	return
}

func (_m *VectorParty) Equals(other common.VectorParty) bool {
	_ = "STUB: not implemented"
	return false
}

// GetBytes provides a mock function with given fields:
func (_m *VectorParty) GetBytes() int64 { _ = "STUB: not implemented"; return 0 }

// GetDataType provides a mock function with given fields:
func (_m *VectorParty) GetDataType() common.DataType {
	_ = "STUB: not implemented"
	return *new(common.DataType)
}

// GetDataValue provides a mock function with given fields: offset
func (_m *VectorParty) GetDataValue(offset int) common.DataValue {
	_ = "STUB: not implemented"
	return *new(common.DataValue)
}

// GetDataValueByRow provides a mock function with given fields: row
func (_m *VectorParty) GetDataValueByRow(row int) common.DataValue {
	_ = "STUB: not implemented"
	return *new(common.DataValue)
}

// GetLength provides a mock function with given fields:
func (_m *VectorParty) GetLength() int { _ = "STUB: not implemented"; return 0 }

// GetNonDefaultValueCount provides a mock function with given fields:
func (_m *VectorParty) GetNonDefaultValueCount() int { _ = "STUB: not implemented"; return 0 }

// GetValidity provides a mock function with given fields: offset
func (_m *VectorParty) GetValidity(offset int) bool { _ = "STUB: not implemented"; return false }

// IsList provides a mock function with given fields:
func (_m *VectorParty) IsList() bool { _ = "STUB: not implemented"; return false }

// Read provides a mock function with given fields: reader, serializer
func (_m *VectorParty) Read(reader io.Reader, serializer common.VectorPartySerializer) error {
	_ = "STUB: not implemented"
	return nil
}

// SafeDestruct provides a mock function with given fields:
func (_m *VectorParty) SafeDestruct() {
	_ = "STUB: not implemented"

	// SetDataValue provides a mock function with given fields: offset, value, countsUpdateMode, counts
	return
}

func (_m *VectorParty) SetDataValue(offset int, value common.DataValue, countsUpdateMode common.ValueCountsUpdateMode, counts ...uint32) {
	_ = "STUB: not implemented"
	return
}

// Slice provides a mock function with given fields: startRow, numRows
func (_m *VectorParty) Slice(startRow int, numRows int) common.SlicedVector {
	_ = "STUB: not implemented"
	return *new(common.SlicedVector)
}

// Write provides a mock function with given fields: writer
func (_m *VectorParty) Write(writer io.Writer) error { _ = "STUB: not implemented"; return nil }
