// Code generated by mockery v1.0.0
package mocks

import (
	shard "github.com/m3db/m3/src/cluster/shard"
	mock "github.com/stretchr/testify/mock"
)

// ShardSet is an autogenerated mock type for the ShardSet type
type ShardSet struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *ShardSet) All() []shard.Shard { _ = "STUB: not implemented"; return nil }

// AllIDs provides a mock function with given fields:
func (_m *ShardSet) AllIDs() []uint32 { _ = "STUB: not implemented"; return nil }
