// Code generated by mockery v1.0.0
package mocks

import (
	context "context"

	common "github.com/uber/aresdb/query/common"

	mock "github.com/stretchr/testify/mock"

	topology "github.com/uber/aresdb/cluster/topology"
)

// DataNodeQueryClient is an autogenerated mock type for the DataNodeQueryClient type
type DataNodeQueryClient struct {
	mock.Mock
}

// Query provides a mock function with given fields: ctx, requestID, host, query, hll
func (_m *DataNodeQueryClient) Query(ctx context.Context, requestID string, host topology.Host, query common.AQLQuery, hll bool) (common.AQLQueryResult, error) {
	_ = "STUB: not implemented"
	return *new(common.AQLQueryResult), nil
}

// QueryRaw provides a mock function with given fields: ctx, requestID, host, query
func (_m *DataNodeQueryClient) QueryRaw(ctx context.Context, requestID string, host topology.Host, query common.AQLQuery) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
