// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/uber/aresdb/datanode/client"

	topology "github.com/uber/aresdb/cluster/topology"
)

// Peer is an autogenerated mock type for the Peer type
type Peer struct {
	mock.Mock
}

// BorrowConnection provides a mock function with given fields: fn
func (_m *Peer) BorrowConnection(fn client.WithConnectionFn) error {
	_ = "STUB: not implemented"
	return nil
}

// Close provides a mock function with given fields:
func (_m *Peer) Close() {
	_ = "STUB: not implemented"

	// Host provides a mock function with given fields:
	return
}

func (_m *Peer) Host() topology.Host { _ = "STUB: not implemented"; return *new(topology.Host) }
