// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/uber/aresdb/datanode/client"
)

// PeerSource is an autogenerated mock type for the PeerSource type
type PeerSource struct {
	mock.Mock
}

// BorrowConnection provides a mock function with given fields: hostIDs, fn
func (_m *PeerSource) BorrowConnection(hostIDs []string, fn client.WithConnectionFn) error {
	_ = "STUB: not implemented"
	return nil
}

// Close provides a mock function with given fields:
func (_m *PeerSource) Close() { _ = "STUB: not implemented"; return }
