//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	common "github.com/uber/aresdb/memstore/common"

	mock "github.com/stretchr/testify/mock"
)

// Job is an autogenerated mock type for the Job type
type Job struct {
	mock.Mock
}

// GetIdentifier provides a mock function with given fields:
func (_m *Job) GetIdentifier() string { _ = "STUB: not implemented"; return "" }

// JobType provides a mock function with given fields:
func (_m *Job) JobType() common.JobType { _ = "STUB: not implemented"; return *new(common.JobType) }

// Run provides a mock function with given fields:
func (_m *Job) Run() error { _ = "STUB: not implemented"; return nil }

// String provides a mock function with given fields:
func (_m *Job) String() string { _ = "STUB: not implemented"; return "" }
