// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	bootstrap "github.com/uber/aresdb/datanode/bootstrap"
	client "github.com/uber/aresdb/datanode/client"

	common "github.com/uber/aresdb/memstore/common"

	memstore "github.com/uber/aresdb/memstore"

	mock "github.com/stretchr/testify/mock"

	topology "github.com/uber/aresdb/cluster/topology"
)

// MemStore is an autogenerated mock type for the MemStore type
type MemStore struct {
	mock.Mock
}

// AddTableShard provides a mock function with given fields: table, shardID, totalShards, needPeerCopy, needPurge
func (_m *MemStore) AddTableShard(table string, shardID int, totalShards int, needPeerCopy bool, needPurge bool) {
	_ = "STUB: not implemented"
	return
}

// Archive provides a mock function with given fields: table, shardID, cutoff, reporter
func (_m *MemStore) Archive(table string, shardID int, cutoff uint32, reporter memstore.ArchiveJobDetailReporter) error {
	_ = "STUB: not implemented"
	return nil
}

// Backfill provides a mock function with given fields: table, shardID, reporter
func (_m *MemStore) Backfill(table string, shardID int, reporter memstore.BackfillJobDetailReporter) error {
	_ = "STUB: not implemented"
	return nil
}

// Bootstrap provides a mock function with given fields: peerSource, origin, topo, topoState, options
func (_m *MemStore) Bootstrap(peerSource client.PeerSource, origin string, topo topology.Topology, topoState *topology.StateSnapshot, options bootstrap.Options) error {
	_ = "STUB: not implemented"
	return nil
}

// FetchSchema provides a mock function with given fields:
func (_m *MemStore) FetchSchema() error { _ = "STUB: not implemented"; return nil }

// GetHostMemoryManager provides a mock function with given fields:
func (_m *MemStore) GetHostMemoryManager() common.HostMemoryManager {
	_ = "STUB: not implemented"
	return *new(common.HostMemoryManager)
}

// GetMemoryUsageDetails provides a mock function with given fields:
func (_m *MemStore) GetMemoryUsageDetails() (map[string]memstore.TableShardMemoryUsage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetScheduler provides a mock function with given fields:
func (_m *MemStore) GetScheduler() memstore.Scheduler {
	_ = "STUB: not implemented"
	return *new(memstore.Scheduler)
}

// GetSchema provides a mock function with given fields: table
func (_m *MemStore) GetSchema(table string) (*common.TableSchema, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSchemas provides a mock function with given fields:
func (_m *MemStore) GetSchemas() map[string]*common.TableSchema {
	_ = "STUB: not implemented"
	return nil
}

// GetTableShard provides a mock function with given fields: table, shardID
func (_m *MemStore) GetTableShard(table string, shardID int) (*memstore.TableShard, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HandleIngestion provides a mock function with given fields: table, shardID, upsertBatch
func (_m *MemStore) HandleIngestion(table string, shardID int, upsertBatch *common.UpsertBatch) error {
	_ = "STUB: not implemented"
	return nil
}

// InitShards provides a mock function with given fields: schedulerOff, shardOwner
func (_m *MemStore) InitShards(schedulerOff bool, shardOwner topology.ShardOwner) {
	_ = "STUB: not implemented"
	return
}

// Lock provides a mock function with given fields:
func (_m *MemStore) Lock() {
	_ = "STUB: not implemented"

	// Purge provides a mock function with given fields: table, shardID, batchIDStart, batchIDEnd, reporter
	return
}

func (_m *MemStore) Purge(table string, shardID int, batchIDStart int, batchIDEnd int, reporter memstore.PurgeJobDetailReporter) error {
	_ = "STUB: not implemented"
	return nil
}

// RLock provides a mock function with given fields:
func (_m *MemStore) RLock() {
	_ = "STUB: not implemented"

	// RUnlock provides a mock function with given fields:
	return
}

func (_m *MemStore) RUnlock() {
	_ = "STUB: not implemented"

	// RemoveTableShard provides a mock function with given fields: table, shardID
	return
}

func (_m *MemStore) RemoveTableShard(table string, shardID int) { _ = "STUB: not implemented"; return }

// Snapshot provides a mock function with given fields: table, shardID, reporter
func (_m *MemStore) Snapshot(table string, shardID int, reporter memstore.SnapshotJobDetailReporter) error {
	_ = "STUB: not implemented"
	return nil
}

// Unlock provides a mock function with given fields:
func (_m *MemStore) Unlock() { _ = "STUB: not implemented"; return }
