//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// RedoLogBrowser is an autogenerated mock type for the RedoLogBrowser type
type RedoLogBrowser struct {
	mock.Mock
}

// ListLogFiles provides a mock function with given fields:
func (_m *RedoLogBrowser) ListLogFiles() ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListUpsertBatch provides a mock function with given fields: creationTime
func (_m *RedoLogBrowser) ListUpsertBatch(creationTime int64) ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadData provides a mock function with given fields: creationTime, upsertBatchOffset, start, length
func (_m *RedoLogBrowser) ReadData(creationTime int64, upsertBatchOffset int64, start int, length int) ([][]interface{}, []string, int, error) {
	_ = "STUB: not implemented"
	return nil, nil, 0, nil
}
