//	Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	memstore "github.com/uber/aresdb/memstore"
	common "github.com/uber/aresdb/memstore/common"

	mock "github.com/stretchr/testify/mock"
)

// Scheduler is an autogenerated mock type for the Scheduler type
type Scheduler struct {
	mock.Mock
}

// DeleteTable provides a mock function with given fields: table, isFactTable
func (_m *Scheduler) DeleteTable(table string, isFactTable bool) { _ = "STUB: not implemented"; return }

// EnableJobType provides a mock function with given fields: jobType, enable
func (_m *Scheduler) EnableJobType(jobType common.JobType, enable bool) {
	_ = "STUB: not implemented"
	return
}

// GetJobDetails provides a mock function with given fields: jobType
func (_m *Scheduler) GetJobDetails(jobType common.JobType) interface{} {
	_ = "STUB: not implemented"
	return nil
}

// IsJobTypeEnabled provides a mock function with given fields: jobType
func (_m *Scheduler) IsJobTypeEnabled(jobType common.JobType) bool {
	_ = "STUB: not implemented"
	return false
}

// Lock provides a mock function with given fields:
func (_m *Scheduler) Lock() {
	_ = "STUB: not implemented"

	// NewArchivingJob provides a mock function with given fields: tableName, shardID, cutoff
	return
}

func (_m *Scheduler) NewArchivingJob(tableName string, shardID int, cutoff uint32) memstore.Job {
	_ = "STUB: not implemented"
	return *new(memstore.Job)
}

// NewBackfillJob provides a mock function with given fields: tableName, shardID
func (_m *Scheduler) NewBackfillJob(tableName string, shardID int) memstore.Job {
	_ = "STUB: not implemented"
	return *new(memstore.Job)
}

// NewPurgeJob provides a mock function with given fields: tableName, shardID, batchIDStart, batchIDEnd
func (_m *Scheduler) NewPurgeJob(tableName string, shardID int, batchIDStart int, batchIDEnd int) memstore.Job {
	_ = "STUB: not implemented"
	return *new(memstore.Job)
}

// NewSnapshotJob provides a mock function with given fields: tableName, shardID
func (_m *Scheduler) NewSnapshotJob(tableName string, shardID int) memstore.Job {
	_ = "STUB: not implemented"
	return *new(memstore.Job)
}

// RLock provides a mock function with given fields:
func (_m *Scheduler) RLock() {
	_ = "STUB: not implemented"

	// RUnlock provides a mock function with given fields:
	return
}

func (_m *Scheduler) RUnlock() {
	_ = "STUB: not implemented"

	// Start provides a mock function with given fields:
	return
}

func (_m *Scheduler) Start() {
	_ = "STUB: not implemented"

	// Stop provides a mock function with given fields:
	return
}

func (_m *Scheduler) Stop() {
	_ = "STUB: not implemented"

	// SubmitJob provides a mock function with given fields: job
	return
}

func (_m *Scheduler) SubmitJob(job memstore.Job) (error, chan error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unlock provides a mock function with given fields:
func (_m *Scheduler) Unlock() { _ = "STUB: not implemented"; return }
