//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	common "github.com/uber/aresdb/memstore/common"

	mock "github.com/stretchr/testify/mock"
)

// sortedColumnIterator is an autogenerated mock type for the sortedColumnIterator type
type sortedColumnIterator struct {
	mock.Mock
}

// count provides a mock function with given fields:
func (_m *sortedColumnIterator) count() uint32 { _ = "STUB: not implemented"; return 0 }

// currentPosition provides a mock function with given fields:
func (_m *sortedColumnIterator) currentPosition() uint32 { _ = "STUB: not implemented"; return 0 }

// currentSkipRows provides a mock function with given fields:
func (_m *sortedColumnIterator) currentSkipRows() []int { _ = "STUB: not implemented"; return nil }

// done provides a mock function with given fields:
func (_m *sortedColumnIterator) done() bool { _ = "STUB: not implemented"; return false }

// index provides a mock function with given fields:
func (_m *sortedColumnIterator) index() int { _ = "STUB: not implemented"; return 0 }

// next provides a mock function with given fields:
func (_m *sortedColumnIterator) next() {
	_ = "STUB: not implemented"

	// nextPosition provides a mock function with given fields:
	return
}

func (_m *sortedColumnIterator) nextPosition() uint32 { _ = "STUB: not implemented"; return 0 }

// read provides a mock function with given fields:
func (_m *sortedColumnIterator) read() {
	_ = "STUB: not implemented"

	// setEndPosition provides a mock function with given fields: pos
	return
}

func (_m *sortedColumnIterator) setEndPosition(pos uint32) {
	_ = "STUB: not implemented"

	// value provides a mock function with given fields:
	return
}

func (_m *sortedColumnIterator) value() common.DataValue {
	_ = "STUB: not implemented"
	return *new(common.DataValue)
}
