// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/memstore/common"

	redolog "github.com/uber/aresdb/redolog"
)

// RedologManager is an autogenerated mock type for the RedologManager type
type RedologManager struct {
	mock.Mock
}

// AppendToRedoLog provides a mock function with given fields: upsertBatch
func (_m *RedologManager) AppendToRedoLog(upsertBatch *common.UpsertBatch) (int64, uint32) {
	_ = "STUB: not implemented"
	return 0, 0
}

// CheckpointRedolog provides a mock function with given fields: cutoff, redoFileCheckpointed, batchOffset
func (_m *RedologManager) CheckpointRedolog(cutoff uint32, redoFileCheckpointed int64, batchOffset uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// Close provides a mock function with given fields:
func (_m *RedologManager) Close() {
	_ = "STUB: not implemented"

	// GetBatchReceived provides a mock function with given fields:
	return
}

func (_m *RedologManager) GetBatchReceived() int { _ = "STUB: not implemented"; return 0 }

// GetBatchRecovered provides a mock function with given fields:
func (_m *RedologManager) GetBatchRecovered() int { _ = "STUB: not implemented"; return 0 }

// GetNumFiles provides a mock function with given fields:
func (_m *RedologManager) GetNumFiles() int { _ = "STUB: not implemented"; return 0 }

// GetTotalSize provides a mock function with given fields:
func (_m *RedologManager) GetTotalSize() int { _ = "STUB: not implemented"; return 0 }

// IsAppendEnabled provides a mock function with given fields:
func (_m *RedologManager) IsAppendEnabled() bool { _ = "STUB: not implemented"; return false }

// Iterator provides a mock function with given fields:
func (_m *RedologManager) Iterator() (redolog.NextUpsertFunc, error) {
	_ = "STUB: not implemented"
	return *new(redolog.NextUpsertFunc), nil
}

// UpdateMaxEventTime provides a mock function with given fields: eventTime, redoFile
func (_m *RedologManager) UpdateMaxEventTime(eventTime uint32, redoFile int64) {
	_ = "STUB: not implemented"
	return
}

// WaitForRecoveryDone provides a mock function with given fields:
func (_m *RedologManager) WaitForRecoveryDone() { _ = "STUB: not implemented"; return }
