// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/uber/aresdb/metastore/common"
)

// MetaStore is an autogenerated mock type for the MetaStore type
type MetaStore struct {
	mock.Mock
}

// AddArchiveBatchVersion provides a mock function with given fields: table, shard, batchID, version, seqNum, batchSize
func (_m *MetaStore) AddArchiveBatchVersion(table string, shard int, batchID int, version uint32, seqNum uint32, batchSize int) error {
	_ = "STUB: not implemented"
	return nil
}

// AddColumn provides a mock function with given fields: table, column, appendToArchivingSortOrder
func (_m *MetaStore) AddColumn(table string, column common.Column, appendToArchivingSortOrder bool) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateTable provides a mock function with given fields: table
func (_m *MetaStore) CreateTable(table *common.Table) error { _ = "STUB: not implemented"; return nil }

// DeleteColumn provides a mock function with given fields: table, column
func (_m *MetaStore) DeleteColumn(table string, column string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteTable provides a mock function with given fields: name
func (_m *MetaStore) DeleteTable(name string) error { _ = "STUB: not implemented"; return nil }

// DeleteTableShard provides a mock function with given fields: table, shard
func (_m *MetaStore) DeleteTableShard(table string, shard int) error {
	_ = "STUB: not implemented"
	return nil
}

// ExtendEnumDict provides a mock function with given fields: table, column, enumCases
func (_m *MetaStore) ExtendEnumDict(table string, column string, enumCases []string) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetArchiveBatchVersion provides a mock function with given fields: table, shard, batchID, cutoff
func (_m *MetaStore) GetArchiveBatchVersion(table string, shard int, batchID int, cutoff uint32) (uint32, uint32, int, error) {
	_ = "STUB: not implemented"
	return 0, 0, 0, nil
}

// GetArchiveBatches provides a mock function with given fields: table, shard, start, end
func (_m *MetaStore) GetArchiveBatches(table string, shard int, start int32, end int32) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetArchivingCutoff provides a mock function with given fields: table, shard
func (_m *MetaStore) GetArchivingCutoff(table string, shard int) (uint32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetBackfillProgressInfo provides a mock function with given fields: table, shard
func (_m *MetaStore) GetBackfillProgressInfo(table string, shard int) (int64, uint32, error) {
	_ = "STUB: not implemented"
	return 0, 0, nil
}

// GetEnumDict provides a mock function with given fields: table, column
func (_m *MetaStore) GetEnumDict(table string, column string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRedoLogCheckpointOffset provides a mock function with given fields: table, shard
func (_m *MetaStore) GetRedoLogCheckpointOffset(table string, shard int) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetRedoLogCommitOffset provides a mock function with given fields: table, shard
func (_m *MetaStore) GetRedoLogCommitOffset(table string, shard int) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetSnapshotProgress provides a mock function with given fields: table, shard
func (_m *MetaStore) GetSnapshotProgress(table string, shard int) (int64, uint32, int32, uint32, error) {
	_ = "STUB: not implemented"
	return 0, 0, 0, 0, nil
}

// GetTable provides a mock function with given fields: name
func (_m *MetaStore) GetTable(name string) (*common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTables provides a mock function with given fields:
func (_m *MetaStore) ListTables() ([]string, error) { _ = "STUB: not implemented"; return nil, nil }

// OverwriteArchiveBatchVersion provides a mock function with given fields: table, shard, batchID, version, seqNum, batchSize
func (_m *MetaStore) OverwriteArchiveBatchVersion(table string, shard int, batchID int, version uint32, seqNum uint32, batchSize int) error {
	_ = "STUB: not implemented"
	return nil
}

// PurgeArchiveBatches provides a mock function with given fields: table, shard, batchIDStart, batchIDEnd
func (_m *MetaStore) PurgeArchiveBatches(table string, shard int, batchIDStart int, batchIDEnd int) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateArchivingCutoff provides a mock function with given fields: table, shard, cutoff
func (_m *MetaStore) UpdateArchivingCutoff(table string, shard int, cutoff uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateBackfillProgress provides a mock function with given fields: table, shard, redoLogFile, offset
func (_m *MetaStore) UpdateBackfillProgress(table string, shard int, redoLogFile int64, offset uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateColumn provides a mock function with given fields: table, column, config
func (_m *MetaStore) UpdateColumn(table string, column string, config common.ColumnConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRedoLogCheckpointOffset provides a mock function with given fields: table, shard, offset
func (_m *MetaStore) UpdateRedoLogCheckpointOffset(table string, shard int, offset int64) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRedoLogCommitOffset provides a mock function with given fields: table, shard, offset
func (_m *MetaStore) UpdateRedoLogCommitOffset(table string, shard int, offset int64) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSnapshotProgress provides a mock function with given fields: table, shard, redoLogFile, upsertBatchOffset, lastReadBatchID, lastReadBatchOffset
func (_m *MetaStore) UpdateSnapshotProgress(table string, shard int, redoLogFile int64, upsertBatchOffset uint32, lastReadBatchID int32, lastReadBatchOffset uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateTable provides a mock function with given fields: table
func (_m *MetaStore) UpdateTable(table common.Table) error { _ = "STUB: not implemented"; return nil }

// UpdateTableConfig provides a mock function with given fields: table, config
func (_m *MetaStore) UpdateTableConfig(table string, config common.TableConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// WatchEnumDictEvents provides a mock function with given fields: table, column, startCase
func (_m *MetaStore) WatchEnumDictEvents(table string, column string, startCase int) (<-chan string, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// WatchShardOwnershipEvents provides a mock function with given fields:
func (_m *MetaStore) WatchShardOwnershipEvents() (<-chan common.ShardOwnership, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// WatchTableListEvents provides a mock function with given fields:
func (_m *MetaStore) WatchTableListEvents() (<-chan []string, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// WatchTableSchemaEvents provides a mock function with given fields:
func (_m *MetaStore) WatchTableSchemaEvents() (<-chan *common.Table, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}
