// Code generated by mockery v1.0.0
package mocks

import (
	common "github.com/uber/aresdb/metastore/common"

	mock "github.com/stretchr/testify/mock"
)

// TableSchemaWatchable is an autogenerated mock type for the TableSchemaWatchable type
type TableSchemaWatchable struct {
	mock.Mock
}

// WatchTableListEvents provides a mock function with given fields:
func (_m *TableSchemaWatchable) WatchTableListEvents() (<-chan []string, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// WatchTableSchemaEvents provides a mock function with given fields:
func (_m *TableSchemaWatchable) WatchTableSchemaEvents() (<-chan *common.Table, chan<- struct{}, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}
