// Code generated by mockery v1.0.0
package mocks

import (
	common "github.com/uber/aresdb/metastore/common"

	mock "github.com/stretchr/testify/mock"
)

// TableSchemaMutator is an autogenerated mock type for the TableSchemaMutator type
type TableSchemaMutator struct {
	mock.Mock
}

// AddColumn provides a mock function with given fields: table, column, appendToArchivingSortOrder
func (_m *TableSchemaMutator) AddColumn(table string, column common.Column, appendToArchivingSortOrder bool) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateTable provides a mock function with given fields: table
func (_m *TableSchemaMutator) CreateTable(table *common.Table) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteColumn provides a mock function with given fields: table, column
func (_m *TableSchemaMutator) DeleteColumn(table string, column string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteTable provides a mock function with given fields: name
func (_m *TableSchemaMutator) DeleteTable(name string) error { _ = "STUB: not implemented"; return nil }

// GetTable provides a mock function with given fields: name
func (_m *TableSchemaMutator) GetTable(name string) (*common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTables provides a mock function with given fields:
func (_m *TableSchemaMutator) ListTables() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateColumn provides a mock function with given fields: table, column, config
func (_m *TableSchemaMutator) UpdateColumn(table string, column string, config common.ColumnConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateTable provides a mock function with given fields: table
func (_m *TableSchemaMutator) UpdateTable(table common.Table) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateTableConfig provides a mock function with given fields: table, config
func (_m *TableSchemaMutator) UpdateTableConfig(table string, config common.TableConfig) error {
	_ = "STUB: not implemented"
	return nil
}
