// Code generated by mockery v1.0.0
package mocks

import (
	common "github.com/uber/aresdb/metastore/common"

	mock "github.com/stretchr/testify/mock"
)

// TableSchemaReader is an autogenerated mock type for the TableSchemaReader type
type TableSchemaReader struct {
	mock.Mock
}

// GetTable provides a mock function with given fields: name
func (_m *TableSchemaReader) GetTable(name string) (*common.Table, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTables provides a mock function with given fields:
func (_m *TableSchemaReader) ListTables() ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
