// Code generated by mockery v1.0.0
package mocks

import (
	common "github.com/uber/aresdb/metastore/common"

	mock "github.com/stretchr/testify/mock"
)

// TableSchemaValidator is an autogenerated mock type for the TableSchemaValidator type
type TableSchemaValidator struct {
	mock.Mock
}

// SetNewTable provides a mock function with given fields: table
func (_m *TableSchemaValidator) SetNewTable(table common.Table) {
	_ = "STUB: not implemented"

	// SetOldTable provides a mock function with given fields: table
	return
}

func (_m *TableSchemaValidator) SetOldTable(table common.Table) {
	_ = "STUB: not implemented"

	// Validate provides a mock function with given fields:
	return
}

func (_m *TableSchemaValidator) Validate() error { _ = "STUB: not implemented"; return nil }
