// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnumMutator is an autogenerated mock type for the EnumMutator type
type EnumMutator struct {
	mock.Mock
}

// ExtendEnumCases provides a mock function with given fields: namespace, table, column, enumCases
func (_m *EnumMutator) ExtendEnumCases(namespace string, table string, column string, enumCases []string) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEnumCases provides a mock function with given fields: namespace, table, column
func (_m *EnumMutator) GetEnumCases(namespace string, table string, column string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
