// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnumReader is an autogenerated mock type for the EnumReader type
type EnumReader struct {
	mock.Mock
}

// GetEnumCases provides a mock function with given fields: namespace, table, column
func (_m *EnumReader) GetEnumCases(namespace string, table string, column string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
