//	Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/controller/models"
)

// IngestionAssignmentMutator is an autogenerated mock type for the IngestionAssignmentMutator type
type IngestionAssignmentMutator struct {
	mock.Mock
}

// AddIngestionAssignment provides a mock function with given fields: namespace, IngestionAssignment
func (_m *IngestionAssignmentMutator) AddIngestionAssignment(namespace string, IngestionAssignment models.IngestionAssignment) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteIngestionAssignment provides a mock function with given fields: namespace, name
func (_m *IngestionAssignmentMutator) DeleteIngestionAssignment(namespace string, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// GetHash provides a mock function with given fields: namespace, subscriber
func (_m *IngestionAssignmentMutator) GetHash(namespace string, subscriber string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetIngestionAssignment provides a mock function with given fields: namespace, name
func (_m *IngestionAssignmentMutator) GetIngestionAssignment(namespace string, name string) (models.IngestionAssignment, error) {
	_ = "STUB: not implemented"
	return *new(models.IngestionAssignment), nil
}

// GetIngestionAssignments provides a mock function with given fields: namespace
func (_m *IngestionAssignmentMutator) GetIngestionAssignments(namespace string) ([]models.IngestionAssignment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateIngestionAssignment provides a mock function with given fields: namespace, IngestionAssignment
func (_m *IngestionAssignmentMutator) UpdateIngestionAssignment(namespace string, IngestionAssignment models.IngestionAssignment) error {
	_ = "STUB: not implemented"
	return nil
}
