//	Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/controller/models"
)

// JobMutator is an autogenerated mock type for the JobMutator type
type JobMutator struct {
	mock.Mock
}

// AddJob provides a mock function with given fields: namespace, job
func (_m *JobMutator) AddJob(namespace string, job models.JobConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteJob provides a mock function with given fields: namespace, name
func (_m *JobMutator) DeleteJob(namespace string, name string) error {
	_ = "STUB: not implemented"
	return nil
}

// GetHash provides a mock function with given fields: namespace
func (_m *JobMutator) GetHash(namespace string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetJob provides a mock function with given fields: namespace, name
func (_m *JobMutator) GetJob(namespace string, name string) (models.JobConfig, error) {
	_ = "STUB: not implemented"
	return *new(models.JobConfig), nil
}

// GetJobs provides a mock function with given fields: namespace
func (_m *JobMutator) GetJobs(namespace string) ([]models.JobConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateJob provides a mock function with given fields: namespace, job
func (_m *JobMutator) UpdateJob(namespace string, job models.JobConfig) error {
	_ = "STUB: not implemented"
	return nil
}
