// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/uber/aresdb/controller/models"
)

// MembershipMutator is an autogenerated mock type for the MembershipMutator type
type MembershipMutator struct {
	mock.Mock
}

// GetHash provides a mock function with given fields: namespace
func (_m *MembershipMutator) GetHash(namespace string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetInstance provides a mock function with given fields: namespace, instanceName
func (_m *MembershipMutator) GetInstance(namespace string, instanceName string) (models.Instance, error) {
	_ = "STUB: not implemented"
	return *new(models.Instance), nil
}

// GetInstances provides a mock function with given fields: namespace
func (_m *MembershipMutator) GetInstances(namespace string) ([]models.Instance, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Join provides a mock function with given fields: namespace, instance
func (_m *MembershipMutator) Join(namespace string, instance models.Instance) error {
	_ = "STUB: not implemented"
	return nil
}

// Leave provides a mock function with given fields: namespace, instanceName
func (_m *MembershipMutator) Leave(namespace string, instanceName string) error {
	_ = "STUB: not implemented"
	return nil
}
