//	Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/controller/models"
)

// SubscriberMutator is an autogenerated mock type for the SubscriberMutator type
type SubscriberMutator struct {
	mock.Mock
}

// GetHash provides a mock function with given fields: namespace
func (_m *SubscriberMutator) GetHash(namespace string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetSubscriber provides a mock function with given fields: namespace, subscriberName
func (_m *SubscriberMutator) GetSubscriber(namespace string, subscriberName string) (models.Subscriber, error) {
	_ = "STUB: not implemented"
	return *new(models.Subscriber), nil
}

// GetSubscribers provides a mock function with given fields: namespace
func (_m *SubscriberMutator) GetSubscribers(namespace string) ([]models.Subscriber, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
