// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
	utils "github.com/uber/aresdb/utils"
)

// DiskStore is an autogenerated mock type for the DiskStore type
type DiskStore struct {
	mock.Mock
}

// DeleteBatchVersions provides a mock function with given fields: table, shard, batchID, batchVersion, seqNum
func (_m *DiskStore) DeleteBatchVersions(table string, shard int, batchID int, batchVersion uint32, seqNum uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteBatches provides a mock function with given fields: table, shard, batchIDStart, batchIDEnd
func (_m *DiskStore) DeleteBatches(table string, shard int, batchIDStart int, batchIDEnd int) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// DeleteColumn provides a mock function with given fields: table, column, shard
func (_m *DiskStore) DeleteColumn(table string, column int, shard int) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteLogFile provides a mock function with given fields: table, shard, creationTime
func (_m *DiskStore) DeleteLogFile(table string, shard int, creationTime int64) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSnapshot provides a mock function with given fields: table, shard, redoLogFile, offset
func (_m *DiskStore) DeleteSnapshot(table string, shard int, redoLogFile int64, offset uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteTableShard provides a mock function with given fields: table, shard
func (_m *DiskStore) DeleteTableShard(table string, shard int) error {
	_ = "STUB: not implemented"
	return nil
}

// ListArchiveBatchVectorPartyFiles provides a mock function with given fields: table, shard, batchID, batchVersion, seqNum
func (_m *DiskStore) ListArchiveBatchVectorPartyFiles(table string, shard int, batchID int, batchVersion uint32, seqNum uint32) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListLogFiles provides a mock function with given fields: table, shard
func (_m *DiskStore) ListLogFiles(table string, shard int) ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSnapshotBatches provides a mock function with given fields: table, shard, redoLogFile, offset
func (_m *DiskStore) ListSnapshotBatches(table string, shard int, redoLogFile int64, offset uint32) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSnapshotVectorPartyFiles provides a mock function with given fields: table, shard, redoLogFile, offset, batchID
func (_m *DiskStore) ListSnapshotVectorPartyFiles(table string, shard int, redoLogFile int64, offset uint32, batchID int) ([]int, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// OpenLogFileForAppend provides a mock function with given fields: table, shard, creationTime
func (_m *DiskStore) OpenLogFileForAppend(table string, shard int, creationTime int64) (utils.WriteSyncCloser, error) {
	_ = "STUB: not implemented"
	return *new(utils.WriteSyncCloser), nil
}

// OpenLogFileForReplay provides a mock function with given fields: table, shard, creationTime
func (_m *DiskStore) OpenLogFileForReplay(table string, shard int, creationTime int64) (utils.ReaderSeekerCloser, error) {
	_ = "STUB: not implemented"
	return *new(utils.ReaderSeekerCloser), nil
}

// OpenSnapshotVectorPartyFileForRead provides a mock function with given fields: table, shard, redoLogFile, offset, batchID, columnID
func (_m *DiskStore) OpenSnapshotVectorPartyFileForRead(table string, shard int, redoLogFile int64, offset uint32, batchID int, columnID int) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// OpenSnapshotVectorPartyFileForWrite provides a mock function with given fields: table, shard, redoLogFile, offset, batchID, columnID
func (_m *DiskStore) OpenSnapshotVectorPartyFileForWrite(table string, shard int, redoLogFile int64, offset uint32, batchID int, columnID int) (utils.WriteSyncCloser, error) {
	_ = "STUB: not implemented"
	return *new(utils.WriteSyncCloser), nil
}

// OpenVectorPartyFileForRead provides a mock function with given fields: table, column, shard, batchID, batchVersion, seqNum
func (_m *DiskStore) OpenVectorPartyFileForRead(table string, column int, shard int, batchID int, batchVersion uint32, seqNum uint32) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// OpenVectorPartyFileForWrite provides a mock function with given fields: table, column, shard, batchID, batchVersion, seqNum
func (_m *DiskStore) OpenVectorPartyFileForWrite(table string, column int, shard int, batchID int, batchVersion uint32, seqNum uint32) (utils.WriteSyncCloser, error) {
	_ = "STUB: not implemented"
	return *new(utils.WriteSyncCloser), nil
}

// TruncateLogFile provides a mock function with given fields: table, shard, creationTime, offset
func (_m *DiskStore) TruncateLogFile(table string, shard int, creationTime int64, offset int64) error {
	_ = "STUB: not implemented"
	return nil
}
