//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package broker

import (
	"net/http"

	memCom "github.com/uber/aresdb/memstore/common"
	"github.com/uber/aresdb/query/common"
	"github.com/uber/aresdb/query/context"
	"github.com/uber/aresdb/query/expr"
)

const (
	nonAggregationQueryLimit = 1000
)

// QueryContext is broker query context
type QueryContext struct {
	AQLQuery              *common.AQLQuery
	IsNonAggregationQuery bool
	ReturnHLLBinary       bool
	Writer                http.ResponseWriter
	Error                 error
	Tables                []*memCom.TableSchema
	TableIDByAlias        map[string]int
	TableSchemaByName     map[string]*memCom.TableSchema

	NumDimsPerDimWidth common.DimCountsPerDimWidth
	// lookup table from enum dimension index to EnumDict, used for postprocessing
	DimensionEnumReverseDicts map[int][]string
	// this should be the same as generated by datanodes. in the future we should pass
	// it down to datanodes
	DimensionVectorIndex []int
	DimRowBytes          int
	RequestID            string

	// helper used to share common codes
	QCHelper *context.QueryContextHelper
}

// NewQueryContext creates new query context
func NewQueryContext(aql *common.AQLQuery, returnHLLBinary bool, w http.ResponseWriter) *QueryContext {
	_ = "STUB: not implemented"
	return nil
}

// GetRewrittenQuery get the rewritten query after query parsing
func (qc *QueryContext) GetRewrittenQuery() common.AQLQuery {
	_ = "STUB: not implemented"
	return *new(common.AQLQuery)
}

// Compile parses expressions into ast, load schema from schema reader, resolve types,
// and collects meta data needed by post processing
func (qc *QueryContext) Compile(tableSchemaReader memCom.TableSchemaReader) {
	_ = "STUB: not implemented"
	return
}

func (qc *QueryContext) readSchema(tableSchemaReader memCom.TableSchemaReader) {
	_ = "STUB: not implemented"
	return
}

// Main table.

// Foreign tables.

// Prevent double locking.

func (qc *QueryContext) releaseSchema() { _ = "STUB: not implemented"; return }

func (qc *QueryContext) processJoins() { _ = "STUB: not implemented"; return }

func (qc *QueryContext) processFilters() { _ = "STUB: not implemented"; return }

func (qc *QueryContext) processMeasures() { _ = "STUB: not implemented"; return }

// ony support 1 measure for now

// in case user forgot to provide limit

func (qc *QueryContext) processDimensions() { _ = "STUB: not implemented"; return }

func (qc *QueryContext) sortDimensionColumns() { _ = "STUB: not implemented"; return }

// record value offset, null offset pair
// null offsets will have to add total dim bytes later

// plus one byte per dimension column for validity

func (qc *QueryContext) getAllColumnsDimension() (columns []common.Dimension) {
	_ = "STUB: not implemented"
	// only main table columns wildcard match supported
	return nil
}

// Rewrite walks the expresison AST and resolves data types bottom up.
// In addition it also translates enum strings and rewrites their predicates.
func (qc *QueryContext) Rewrite(expression expr.Expr) expr.Expr {
	_ = "STUB: not implemented"
	return *new(expr.Expr)
}

func (qc *QueryContext) InitQCHelper() { _ = "STUB: not implemented"; return }

func (qc *QueryContext) GetSchema(tableID int) *memCom.TableSchema {
	_ = "STUB: not implemented"
	return nil
}

func (qc *QueryContext) GetTableID(alias string) (int, bool) {
	_ = "STUB: not implemented"
	return 0, false
}

func (qc *QueryContext) GetQuery() *common.AQLQuery { _ = "STUB: not implemented"; return nil }

func (qc *QueryContext) SetError(err error) { _ = "STUB: not implemented"; return }

func (qc *QueryContext) IsDataOnly() bool { _ = "STUB: not implemented"; return false }
