// Code generated by mockery v1.0.0
package mocks

import (
	client "github.com/m3db/m3/src/cluster/client"
	mock "github.com/stretchr/testify/mock"

	services "github.com/m3db/m3/src/cluster/services"

	topology "github.com/uber/aresdb/cluster/topology"

	utils "github.com/uber/aresdb/utils"
)

// DynamicOptions is an autogenerated mock type for the DynamicOptions type
type DynamicOptions struct {
	mock.Mock
}

// ConfigServiceClient provides a mock function with given fields:
func (_m *DynamicOptions) ConfigServiceClient() client.Client {
	_ = "STUB: not implemented"
	return *new(client.Client)
}

// InstrumentOptions provides a mock function with given fields:
func (_m *DynamicOptions) InstrumentOptions() utils.Options {
	_ = "STUB: not implemented"
	return *new(utils.Options)
}

// QueryOptions provides a mock function with given fields:
func (_m *DynamicOptions) QueryOptions() services.QueryOptions {
	_ = "STUB: not implemented"
	return *new(services.QueryOptions)
}

// ServiceID provides a mock function with given fields:
func (_m *DynamicOptions) ServiceID() services.ServiceID {
	_ = "STUB: not implemented"
	return *new(services.ServiceID)
}

// ServicesOverrideOptions provides a mock function with given fields:
func (_m *DynamicOptions) ServicesOverrideOptions() services.OverrideOptions {
	_ = "STUB: not implemented"
	return *new(services.OverrideOptions)
}

// SetConfigServiceClient provides a mock function with given fields: c
func (_m *DynamicOptions) SetConfigServiceClient(c client.Client) topology.DynamicOptions {
	_ = "STUB: not implemented"
	return *new(topology.DynamicOptions)
}

// SetInstrumentOptions provides a mock function with given fields: value
func (_m *DynamicOptions) SetInstrumentOptions(value utils.Options) topology.DynamicOptions {
	_ = "STUB: not implemented"
	return *new(topology.DynamicOptions)
}

// SetQueryOptions provides a mock function with given fields: value
func (_m *DynamicOptions) SetQueryOptions(value services.QueryOptions) topology.DynamicOptions {
	_ = "STUB: not implemented"
	return *new(topology.DynamicOptions)
}

// SetServiceID provides a mock function with given fields: s
func (_m *DynamicOptions) SetServiceID(s services.ServiceID) topology.DynamicOptions {
	_ = "STUB: not implemented"
	return *new(topology.DynamicOptions)
}

// SetServicesOverrideOptions provides a mock function with given fields: opts
func (_m *DynamicOptions) SetServicesOverrideOptions(opts services.OverrideOptions) topology.DynamicOptions {
	_ = "STUB: not implemented"
	return *new(topology.DynamicOptions)
}

// Validate provides a mock function with given fields:
func (_m *DynamicOptions) Validate() error { _ = "STUB: not implemented"; return nil }
