// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// DynamicTopology is an autogenerated mock type for the DynamicTopology type
type DynamicTopology struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *DynamicTopology) Close() {
	_ = "STUB: not implemented"

	// Get provides a mock function with given fields:
	return
}

func (_m *DynamicTopology) Get() topology.Map { _ = "STUB: not implemented"; return *new(topology.Map) }

// MarkShardsAvailable provides a mock function with given fields: instanceID, shardIDs
func (_m *DynamicTopology) MarkShardsAvailable(instanceID string, shardIDs ...uint32) error {
	_ = "STUB: not implemented"
	return nil
}

// Watch provides a mock function with given fields:
func (_m *DynamicTopology) Watch() (topology.MapWatch, error) {
	_ = "STUB: not implemented"
	return *new(topology.MapWatch), nil
}
