// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// HealthTrackingDynamicTopoloy is an autogenerated mock type for the HealthTrackingDynamicTopoloy type
type HealthTrackingDynamicTopoloy struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *HealthTrackingDynamicTopoloy) Close() {
	_ = "STUB: not implemented"

	// Get provides a mock function with given fields:
	return
}

func (_m *HealthTrackingDynamicTopoloy) Get() topology.Map {
	_ = "STUB: not implemented"
	return *new(topology.Map)
}

// MarkHostHealthy provides a mock function with given fields: host
func (_m *HealthTrackingDynamicTopoloy) MarkHostHealthy(host topology.Host) error {
	_ = "STUB: not implemented"
	return nil
}

// MarkHostUnhealthy provides a mock function with given fields: host
func (_m *HealthTrackingDynamicTopoloy) MarkHostUnhealthy(host topology.Host) error {
	_ = "STUB: not implemented"
	return nil
}

// Watch provides a mock function with given fields:
func (_m *HealthTrackingDynamicTopoloy) Watch() (topology.MapWatch, error) {
	_ = "STUB: not implemented"
	return *new(topology.MapWatch), nil
}
