// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	shard "github.com/uber/aresdb/cluster/shard"

	topology "github.com/uber/aresdb/cluster/topology"
)

// HostShardSet is an autogenerated mock type for the HostShardSet type
type HostShardSet struct {
	mock.Mock
}

// Host provides a mock function with given fields:
func (_m *HostShardSet) Host() topology.Host { _ = "STUB: not implemented"; return *new(topology.Host) }

// ShardSet provides a mock function with given fields:
func (_m *HostShardSet) ShardSet() shard.ShardSet {
	_ = "STUB: not implemented"
	return *new(shard.ShardSet)
}
