// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Host is an autogenerated mock type for the Host type
type Host struct {
	mock.Mock
}

// Address provides a mock function with given fields:
func (_m *Host) Address() string { _ = "STUB: not implemented"; return "" }

// ID provides a mock function with given fields:
func (_m *Host) ID() string { _ = "STUB: not implemented"; return "" }

// String provides a mock function with given fields:
func (_m *Host) String() string { _ = "STUB: not implemented"; return "" }
