// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// Initializer is an autogenerated mock type for the Initializer type
type Initializer struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *Initializer) Init() (topology.Topology, error) {
	_ = "STUB: not implemented"
	return *new(topology.Topology), nil
}

// TopologyIsSet provides a mock function with given fields:
func (_m *Initializer) TopologyIsSet() (bool, error) { _ = "STUB: not implemented"; return false, nil }
