// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	shard "github.com/uber/aresdb/cluster/shard"

	topology "github.com/uber/aresdb/cluster/topology"
)

// Map is an autogenerated mock type for the Map type
type Map struct {
	mock.Mock
}

// HostShardSets provides a mock function with given fields:
func (_m *Map) HostShardSets() []topology.HostShardSet { _ = "STUB: not implemented"; return nil }

// Hosts provides a mock function with given fields:
func (_m *Map) Hosts() []topology.Host { _ = "STUB: not implemented"; return nil }

// HostsLen provides a mock function with given fields:
func (_m *Map) HostsLen() int { _ = "STUB: not implemented"; return 0 }

// LookupHostShardSet provides a mock function with given fields: hostID
func (_m *Map) LookupHostShardSet(hostID string) (topology.HostShardSet, bool) {
	_ = "STUB: not implemented"
	return *new(topology.HostShardSet), false
}

// Replicas provides a mock function with given fields:
func (_m *Map) Replicas() int { _ = "STUB: not implemented"; return 0 }

// RouteShard provides a mock function with given fields: _a0
func (_m *Map) RouteShard(_a0 uint32) ([]topology.Host, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ShardSet provides a mock function with given fields:
func (_m *Map) ShardSet() shard.ShardSet { _ = "STUB: not implemented"; return *new(shard.ShardSet) }
