// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// MapProvider is an autogenerated mock type for the MapProvider type
type MapProvider struct {
	mock.Mock
}

// TopologyMap provides a mock function with given fields:
func (_m *MapProvider) TopologyMap() (topology.Map, error) {
	_ = "STUB: not implemented"
	return *new(topology.Map), nil
}
