// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// MapWatch is an autogenerated mock type for the MapWatch type
type MapWatch struct {
	mock.Mock
}

// C provides a mock function with given fields:
func (_m *MapWatch) C() <-chan struct{} { _ = "STUB: not implemented"; return nil }

// Close provides a mock function with given fields:
func (_m *MapWatch) Close() {
	_ = "STUB: not implemented"

	// Get provides a mock function with given fields:
	return
}

func (_m *MapWatch) Get() topology.Map { _ = "STUB: not implemented"; return *new(topology.Map) }
