// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	shard "github.com/uber/aresdb/cluster/shard"

	topology "github.com/uber/aresdb/cluster/topology"
)

// StaticOptions is an autogenerated mock type for the StaticOptions type
type StaticOptions struct {
	mock.Mock
}

// HostShardSets provides a mock function with given fields:
func (_m *StaticOptions) HostShardSets() []topology.HostShardSet {
	_ = "STUB: not implemented"
	return nil
}

// Replicas provides a mock function with given fields:
func (_m *StaticOptions) Replicas() int { _ = "STUB: not implemented"; return 0 }

// SetHostShardSets provides a mock function with given fields: value
func (_m *StaticOptions) SetHostShardSets(value []topology.HostShardSet) topology.StaticOptions {
	_ = "STUB: not implemented"
	return *new(topology.StaticOptions)
}

// SetReplicas provides a mock function with given fields: value
func (_m *StaticOptions) SetReplicas(value int) topology.StaticOptions {
	_ = "STUB: not implemented"
	return *new(topology.StaticOptions)
}

// SetShardSet provides a mock function with given fields: value
func (_m *StaticOptions) SetShardSet(value shard.ShardSet) topology.StaticOptions {
	_ = "STUB: not implemented"
	return *new(topology.StaticOptions)
}

// ShardSet provides a mock function with given fields:
func (_m *StaticOptions) ShardSet() shard.ShardSet {
	_ = "STUB: not implemented"
	return *new(shard.ShardSet)
}

// Validate provides a mock function with given fields:
func (_m *StaticOptions) Validate() error { _ = "STUB: not implemented"; return nil }
