// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	topology "github.com/uber/aresdb/cluster/topology"
)

// Topology is an autogenerated mock type for the Topology type
type Topology struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Topology) Close() {
	_ = "STUB: not implemented"

	// Get provides a mock function with given fields:
	return
}

func (_m *Topology) Get() topology.Map { _ = "STUB: not implemented"; return *new(topology.Map) }

// Watch provides a mock function with given fields:
func (_m *Topology) Watch() (topology.MapWatch, error) {
	_ = "STUB: not implemented"
	return *new(topology.MapWatch), nil
}
