// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	bootstrap "github.com/uber/aresdb/datanode/bootstrap"
	client "github.com/uber/aresdb/datanode/client"

	mock "github.com/stretchr/testify/mock"

	topology "github.com/uber/aresdb/cluster/topology"
)

// Bootstrapable is an autogenerated mock type for the Bootstrapable type
type Bootstrapable struct {
	mock.Mock
}

// Bootstrap provides a mock function with given fields: peerSource, origin, topo, topoState, options
func (_m *Bootstrapable) Bootstrap(peerSource client.PeerSource, origin string, topo topology.Topology, topoState *topology.StateSnapshot, options bootstrap.Options) error {
	_ = "STUB: not implemented"
	return nil
}
